<a href="https://colab.research.google.com/github/Pandatoey/LAB229351/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_208424Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.optimize import linprog

In [ ]:
a = np.ones(10) #เวกเตอร์ที่มีแต่เลข 1 01ตัว
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [ ]:
c = np.random.rand(5,6)
c

array([[0.40291463, 0.59684237, 0.29871418, 0.4830836 , 0.4723004 ,
        0.93218064],
       [0.76958788, 0.6056477 , 0.15105994, 0.50356695, 0.64000831,
        0.71409735],
       [0.85361024, 0.75427253, 0.87619163, 0.50869344, 0.3833651 ,
        0.65187076],
       [0.49690773, 0.82487942, 0.42988734, 0.22948375, 0.41320819,
        0.06792561],
       [0.23025293, 0.44793396, 0.85665814, 0.85980472, 0.42922409,
        0.94039977]])

In [ ]:
d = np.random.randn(5,6)
d

array([[ 0.21220126, -0.29528856,  1.4080206 ,  1.7053774 ,  0.17754717,
         1.01767109],
       [ 0.32042344,  0.69947695, -0.28161785,  0.98322856,  0.08597434,
         1.43885436],
       [-0.81287596, -0.20985247,  1.8683062 ,  0.25924716, -0.45139097,
         0.9912673 ],
       [-0.65730165,  0.56003603,  0.40175348,  0.83489857, -0.08220252,
         0.64122894],
       [-1.05880957,  0.12651147,  0.51032898,  1.33548704, -0.42624825,
        -2.28824818]])

In [ ]:
#เอาเมทริกมาต่อกัน
e = np.random.randn(3,4)
f = np.random.randn(3,4)

#ต่อกันแนวตั้ง
g = np.vstack([e,f])

print(e)
print(f)
print(g)

[[ 0.96622413 -0.74601658 -0.73983993  0.18929549]
 [-0.55054747  1.19253977  1.78763817  1.20306848]
 [ 1.28531475 -1.81991457 -1.18053995  1.55218524]]
[[-2.77601147  0.05695595  1.58733267  0.27848849]
 [-1.43891319  1.86811737  0.58271374 -0.50296065]
 [ 0.2444088   0.20695933 -1.50268527 -0.4647323 ]]
[[ 0.96622413 -0.74601658 -0.73983993  0.18929549]
 [-0.55054747  1.19253977  1.78763817  1.20306848]
 [ 1.28531475 -1.81991457 -1.18053995  1.55218524]
 [-2.77601147  0.05695595  1.58733267  0.27848849]
 [-1.43891319  1.86811737  0.58271374 -0.50296065]
 [ 0.2444088   0.20695933 -1.50268527 -0.4647323 ]]


In [ ]:
#ต่อกันเปนแนวนอน
h = np.hstack([e,f])
h

array([[ 0.96622413, -0.74601658, -0.73983993,  0.18929549, -2.77601147,
         0.05695595,  1.58733267,  0.27848849],
       [-0.55054747,  1.19253977,  1.78763817,  1.20306848, -1.43891319,
         1.86811737,  0.58271374, -0.50296065],
       [ 1.28531475, -1.81991457, -1.18053995,  1.55218524,  0.2444088 ,
         0.20695933, -1.50268527, -0.4647323 ]])

### setup : laptop company
Two types of laptop
- standard laptop: \$300 per unit sold
- Gaming laptop: \$500 per unit sold

Goal: Maximize profit

constraints:

1. we have 1800 assembly hours. 3 hours for a standard laptop, 4 hours for a Gaming laptop

2. we have 350 GPUs , which is only used to build a gaming laptop

3. we have 1000 testing hours. both types of laptop require 1 hours of tesing

In [ ]:
result = linprog(
    c = [-300,-500], #maximize 300*x1 + 500*x2 = minimize -300*x1 - 500*x2
    A_ub = np.array([[3,4], #constraint 1: 3*x1 + 4*x2 <= 1800
                     [0,1], #constraint 2: 0*x1 + 1*x2 <= 350
                     [1,1]]), #constraint 3: 1*x1 + 1*x2 <= 1000

    b_ub = [1800,350,1000],
    bounds= [(0,None),(0,None)]
)

In [ ]:
result

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -215000.0
              x: [ 1.333e+02  3.500e+02]
            nit: 0
          lower:  residual: [ 1.333e+02  3.500e+02]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  5.167e+02]
                 marginals: [-1.000e+02 -1.000e+02 -0.000e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

data $(x_1,y_1),(x_2,y_2), \ldots, (x_n,y_n)$.

Model $\hat{y} = \beta_1 x_1 + \beta_2 x_2 + \ldots + (\beta_m,x_m) = \beta^\top x$ ,
Where $\beta = [\beta_1,\ldots,\beta_m]^\top$ and $x = [x_1, \ldots, x_m]^\top$

Optimize for $\beta$ by minimizing $\sum_{i=1}^n | y_i - \beta^\top x_i |$ with respect to $\beta$.
**L1 regression**

Trick : use $|z| = \max\{z,-z\}$.

Let $u_i = |y_i - \beta^\top x_i|$. Then, $u_i \ge y_i - \beta^\top x_i$ and $u_i \ge -(y_i - \beta^\top x_i)$.

LP : $\min_{u,\beta} \sum_{i=1}^n u_i$ subject to:

1. $u_i \ge y_i - \beta^\top x_i$ or $u_i + \beta^\top x_i \ge y_i$ for $i=1\ldots,n$

2. $u_i \ge (y_i - \beta^\top x_i)$ or $u_i - \beta^\top x_i \ge y_i$ for $i=1\ldots,n$

3. $u_i \ge 0$ for $i=1\ldots,n$

Let $I$ be $n \times n$ identity matrix.
Let $x$ be the matrix with $x_i$ in the $i$-th row.
Let $u = [u_1,u_2,\ldots,u_n]^\top$

New constraint:
1. $-Iu - x \beta \le - y$
2. $-Iu + x \beta \le  y$
3. $u \ge 0$

### Simulate data

In [ ]:
n,m = 50, 5
X = np.random.randn(n,m)
beta = np.array([2.0,4.0,6.0,8.0,10.0])
y = X @ beta + 0.2 * np.random.randn(n)

In [ ]:
y

array([ -2.21064485, -14.02824673, -22.09449541,  13.18613076,
        -1.10011862, -16.36861842,  21.17860602,   8.25029783,
       -11.09612847,   9.80892798, -27.13346256, -40.9117988 ,
       -18.29577749,   7.16531608,  -1.38388066, -14.35934725,
        35.1245195 , -13.25398423,  -2.26105662, -11.44508144,
        14.57997296, -27.76256988, -11.90761301, -13.44116521,
        26.42920894,   1.57086302,   8.12758487,  11.7009556 ,
        16.97029262, -22.23580513,   8.30640675,  -9.87834089,
         4.65008763,  19.64978746, -27.43181101,   1.00775624,
        26.47402092,  14.35306861, -18.82230868,   8.56049968,
         4.26032564, -12.06856722,  -3.15992035, -25.85271282,
       -12.59975228,  26.34462454,   2.66669343, -16.42855229,
        -1.06322471, -15.71135361])

In [ ]:
[50]*10

[50, 50, 50, 50, 50, 50, 50, 50, 50, 50]

In [ ]:
result = linprog(
    c = np.hstack([np.ones(n),np.zeros(m)]),
    A_ub = np.vstack([np.hstack([-np.eye(n),-X]), np.hstack([-np.eye(n),X])]),
    b_ub = np.hstack([-y,y]),
    bounds = [(0,None)]*(m + n)
)


In [ ]:
result

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 7.6411550781958875
              x: [ 3.996e-02  1.136e-01 ...  7.999e+00  1.002e+01]
            nit: 58
          lower:  residual: [ 3.996e-02  1.136e-01 ...  7.999e+00
                              1.002e+01]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [-1.000e+00 -1.000e+00 ... -9.165e-01
                             -3.008e-01]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip

In [ ]:
beta

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
estimated_beta = result.x[-5:]
estimated_beta

array([ 2.002927  ,  3.95954241,  6.03131038,  7.99933766, 10.01894073])