<a href="https://colab.research.google.com/github/Pandatoey/LAB229351/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [38]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [39]:
A = torch.tensor(2)
print(A)

B = torch.tensor(3)
print(A + B)

tensor(2)
tensor(5)


### Convert a tensor to scalar

In [40]:
C = B.item()
print(C)

3


### Creating 2D tensor

In [41]:
C = B.item()
print(C)

3


## Tensor and Numpy

### Convert from tensor to numpy array

In [42]:
B = A.numpy()
B

array(2)

### Convert from numpy array to tensor

In [43]:
C = torch.from_numpy(B)
C

tensor(2)

## PyTorch and GPU

check if GPU is available

In [44]:
torch.cuda.is_available()

True

In [45]:
C.device

device(type='cpu')

In [46]:
D = C.cuda()
D

tensor(2, device='cuda:0')

In [47]:
D.device

device(type='cuda', index=0)

In [48]:
C + D

tensor(4, device='cuda:0')

In [49]:
#D.numpy()
E = D.cpu().numpy()
E

array(2)

## Basic operations

In [50]:
D ** 2

tensor(4, device='cuda:0')

In [51]:
D.cpu() * np.array([1,2])

/tmp/ipython-input-1707415638.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1,2])


tensor([2, 4])

### Matrix multiplication

In [52]:
A = torch.tensor([[4 ,5],
                  [8, 9]])
B = torch.tensor([[1 ,4],
                  [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [53]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [54]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [55]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [56]:
# tensor ที่มีแต่เลข 0
a = torch.zeros(1, 2, 3)
a

# tensor ที่มีแต่เลข 1
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [57]:
# Identity matrix
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [58]:
# Random
R1 = torch.rand(2, 3) # Uniform dist.
R1

tensor([[0.3978, 0.4157, 0.2368],
        [0.8701, 0.1539, 0.4199]])

In [59]:
R2 = torch.randn(2, 3) # Normal dist.
R2

tensor([[ 0.7003, -0.1992,  0.2113],
        [ 0.7899, -0.4817,  0.3641]])

In [60]:
# vector เรียงลำดับกัน
a = torch.arange(1, 10, 2)
a

tensor([1, 3, 5, 7, 9])

## Tensor's shape

### Checking the shape of a tensor

In [61]:
u = torch.arange(6)
print(u.shape)
u

torch.Size([6])


tensor([0, 1, 2, 3, 4, 5])

### Changing the shape of a tensor

In [62]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [63]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [64]:
a = torch.arange(4)
b = torch.arange(4) + 1
a, b

(tensor([0, 1, 2, 3]), tensor([1, 2, 3, 4]))

In [65]:
c = torch.stack([a, b], axis = 0) #stack แบบแถว
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [66]:
d = torch.stack([a, b], axis = 1) #stack แบบหลัก
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [67]:
# concatenate
e = torch.cat([a, b], axis = 0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

### Squeezing a tensor (removing an extra dimension)

In [68]:
A = torch.zeros(1, 2, 3)

In [69]:
# Remove 1st axis
B = A.squeeze() # defaut คือแกนที่มี 1 แถว
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [70]:
C = B.unsqueeze(axis = 0)
C.shape

torch.Size([1, 2, 3])

## Indexing

In [71]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [72]:
# Create three random  N(0,1)  tensors: X
X = torch.randn(200, 7)
print('X.shape :', X.shape)

# Create three random  N(0,1)  tensors: b
b = torch.randn(8, 1)
print('b.shape :', b.shape)

# Create three random  N(0,1)  tensors: e
e = torch.randn(200, 1)
print('e.shape :', e.shape)

X.shape : torch.Size([200, 7])
b.shape : torch.Size([8, 1])
e.shape : torch.Size([200, 1])


In [73]:
# Create a tensor that contains only 1's with shape (200, 1).
ones = torch.ones(200, 1)
print(ones.shape)

torch.Size([200, 1])


In [74]:
# Modify tensor X by adding the tensor in 2. as the first column
X = torch.cat([ones, X], axis = 1)
print(X.shape)
print(X)

torch.Size([200, 8])
tensor([[ 1.0000,  1.5552,  0.7847,  ...,  2.4114,  1.6540, -1.0137],
        [ 1.0000, -0.2305,  1.0897,  ...,  0.0838,  1.3540, -0.1623],
        [ 1.0000, -0.1920,  0.2825,  ...,  0.2956,  1.2619, -1.0560],
        ...,
        [ 1.0000, -1.0883, -1.8027,  ...,  1.3579,  0.3291,  0.9386],
        [ 1.0000,  1.1682, -2.8143,  ..., -0.5125, -0.2619,  0.5467],
        [ 1.0000,  0.0604,  0.7553,  ..., -0.7027,  0.6102, -0.6564]])


In [75]:
# Compute y using the following formula
y = torch.mm(X, b) + e

In [76]:
# Fit a linear regression to the data X and y and obtain a tensor of estimated coefficient b_hat
X_inv = torch.inverse(X.t() @ X)
b_hat = X_inv @ X.t() @ y
print(b_hat)

tensor([[ 0.9185],
        [-1.1745],
        [-1.2846],
        [ 0.0924],
        [-0.3668],
        [ 0.4417],
        [-0.2784],
        [ 0.5274]])


In [77]:
# Compute the predictions
y_hat = X @ b_hat
print(y_hat.shape)

torch.Size([200, 1])


In [78]:
# Convert both y and y_hat from tensor to Numpy array and calculate MSE

# Convert to numpy
y = y.numpy()
y_hat = y_hat.numpy()


# Calculate MSE
mse = np.mean((y - y_hat)**2)
print('MSE:',mse)

MSE: 0.9332602
