<a href="https://colab.research.google.com/github/Pandatoey/LAB229351/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [6]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [7]:
a = torch.tensor(2)
print(a)

b = torch.tensor(3)
print(a + b)

tensor(2)
tensor(5)


### Convert a tensor to scalar

In [8]:
c = b.item()
print(c)

3


### Creating 2D tensor

In [9]:
c = b.item()
print(c)

3


## Tensor and Numpy

### Convert from tensor to numpy array

In [10]:
B = A.numpy()
B

NameError: name 'A' is not defined

### Convert from numpy array to tensor

In [50]:
C = torch.from_numpy(B)
C

TypeError: expected np.ndarray (got Tensor)

## PyTorch and GPU

check if GPU is available

In [49]:
torch.cuda.is_available()

True

In [48]:
C.device

NameError: name 'C' is not defined

In [47]:
D = C.cuda()
D

NameError: name 'C' is not defined

In [46]:
D.device

NameError: name 'D' is not defined

In [45]:
C + D

NameError: name 'C' is not defined

In [44]:
#D.numpy()
E = D.cpu().numpy()
E

NameError: name 'D' is not defined

## Basic operations

In [43]:
D ** 2

NameError: name 'D' is not defined

In [42]:
D.cpu() * np.array([1,2])

NameError: name 'D' is not defined

### Matrix multiplication

In [41]:
A = torch.tensor([[4 ,5],
                  [8, 9]])
B = torch.tensor([[1 ,4],
                  [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [40]:
torch.mm(A, B)

NameError: name 'B' is not defined

In [39]:
A @ B

NameError: name 'B' is not defined

### Matrix transpose

In [38]:
A.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

## Creating a specific type of tensor

In [37]:
# tensor ที่มีแต่เลข 0
a = torch.zeros(1, 2, 3)
a

# tensor ที่มีแต่เลข 1
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [36]:
# Identity matrix
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [35]:
# Random
R1 = torch.rand(2, 3) # Uniform dist.
R1

tensor([[0.1119, 0.7367, 0.5476],
        [0.0812, 0.9868, 0.5916]])

In [34]:
R2 = torch.randn(2, 3) # Normal dist.
R2

tensor([[-0.7605,  0.5841, -0.2214],
        [-3.2531, -1.0877, -1.0619]])

In [33]:
# vector เรียงลำดับกัน
a = torch.arange(1, 10, 2)
a

tensor([1, 3, 5, 7, 9])

## Tensor's shape

### Checking the shape of a tensor

In [32]:
u = torch.arange(6)
print(u.shape)
u

torch.Size([6])


tensor([0, 1, 2, 3, 4, 5])

### Changing the shape of a tensor

In [31]:
v = u.reshape(2, 3)
v

NameError: name 'u' is not defined

In [30]:
w = u.view(3, 2)
w

NameError: name 'u' is not defined

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [29]:
a = torch.arange(4)
b = torch.arange(4) + 1
a, b

(tensor([0, 1, 2, 3]), tensor([1, 2, 3, 4]))

In [13]:
c = torch.stack([a, b], axis = 0) #stack แบบแถว
c

tensor([2, 3])

In [28]:
d = torch.stack([a, b], axis = 1) #stack แบบหลัก
d

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [27]:
# concatenate
e = torch.cat([a, b], axis = 0)
e

RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

### Squeezing a tensor (removing an extra dimension)

In [26]:
A = torch.zeros(1, 2, 3)

In [25]:
# Remove 1st axis
B = A.squeeze() # defaut คือแกนที่มี 1 แถว
B.shape

NameError: name 'A' is not defined

### Unsqueezing a tensor (adding an extra dimension)

In [24]:
C = B.unsqueeze(axis = 0)
C.shape

NameError: name 'B' is not defined

## Indexing

In [23]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [15]:
# Create three random  N(0,1)  tensors: X
X = torch.randn(200, 7)
print('X.shape :', X.shape)

# Create three random  N(0,1)  tensors: b
b = torch.randn(8, 1)
print('b.shape :', b.shape)

# Create three random  N(0,1)  tensors: e
e = torch.randn(200, 1)
print('e.shape :', e.shape)

X.shape : torch.Size([200, 7])
b.shape : torch.Size([8, 1])
e.shape : torch.Size([200, 1])


In [16]:
# Create a tensor that contains only 1's with shape (200, 1).
ones = torch.ones(200, 1)
print(ones.shape)

torch.Size([200, 1])


In [17]:
# Modify tensor X by adding the tensor in 2. as the first column
X = torch.cat([ones, X], axis = 1)
print(X.shape)
print(X)

torch.Size([200, 8])
tensor([[ 1.0000,  1.0504,  0.1749,  ...,  0.5624, -0.9991,  2.3610],
        [ 1.0000,  0.5857, -0.6045,  ..., -1.1063, -0.5166, -1.1481],
        [ 1.0000, -0.1038,  1.3776,  ..., -0.5090,  0.5276, -0.1449],
        ...,
        [ 1.0000,  0.6866, -0.6850,  ..., -1.6835, -0.8507, -0.5162],
        [ 1.0000, -0.9574, -0.2567,  ...,  0.9993,  0.9560, -0.6458],
        [ 1.0000,  0.0483, -0.4977,  ...,  0.5896, -0.0933,  0.5843]])


In [19]:
# Compute y using the following formula
y = torch.mm(X, b) + e

In [20]:
# Fit a linear regression to the data X and y and obtain a tensor of estimated coefficient b_hat
X_inv = torch.inverse(X.t() @ X)
b_hat = X_inv @ X.t() @ y
print(b_hat)

tensor([[ 0.5398],
        [ 1.0869],
        [-0.9565],
        [ 0.9837],
        [-1.4715],
        [ 1.5707],
        [-2.2454],
        [ 0.9937]])


In [21]:
# Compute the predictions
y_hat = X @ b_hat
print(y_hat.shape)

torch.Size([200, 1])


In [22]:
# Convert both y and y_hat from tensor to Numpy array and calculate MSE

# Convert to numpy
y = y.numpy()
y_hat = y_hat.numpy()


# Calculate MSE
mse = np.mean((y - y_hat)**2)
print('MSE:',mse)

MSE: 0.7853683
